[package]
name = "zkvm-tool"
edition.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }

alloy-primitives.workspace = true

zktls-program-core.workspace = true

serde_json.workspace = true
