[package]
name = "t3zktls-program-r0"
version.workspace = true
edition.workspace = true

[build-dependencies]
risc0-build = { version = "1.1.2" }
risc0-build-ethereum = { version = "1.1.2" }

[package.metadata.risc0]
methods = ["tls-r0"]